# -*- coding: utf-8 -*-
"""House_price_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIFjrI8D87I-Yq_HgDHBx9NkkvHYI5_j
"""

# Dependancies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.linear_model import LinearRegression,Ridge,ElasticNet
from sklearn.metrics import r2_score
import pickle

# reading data
data = pd.read_csv(r'D:\Projects\Prodigy-Projects\PRODIGY_ML_01\Data\train.csv')
X = data.drop('SalePrice',axis=1)
y = data['SalePrice']

# merging related columns
X['TotalSF'] = X['TotalBsmtSF']+X['1stFlrSF']+X['2ndFlrSF']
X['Age'] = X['YrSold']-X['YearBuilt']

X=X.drop(['TotalBsmtSF','1stFlrSF','2ndFlrSF','YrSold','YearBuilt'],axis=1)

# splitting using train test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# dropping columns which are not much significant
X_train = X_train.drop(['Id','Alley','PoolQC','Fence','Utilities','MiscFeature','MiscVal'],axis=1)
X_test = X_test.drop(['Id','Alley','PoolQC','Fence','Utilities','MiscFeature','MiscVal'],axis=1)

# categories
numerical_features = X_train.select_dtypes(include=['int64','float64']).columns.to_list()
ordinal_features = [
    'LotShape', 'LandSlope', 'ExterQual', 'ExterCond',
    'BsmtQual', 'BsmtCond', 'BsmtExposure',
    'BsmtFinType1', 'BsmtFinType2', 'HeatingQC',
    'KitchenQual', 'Functional', 'FireplaceQu',
    'GarageFinish', 'GarageQual', 'GarageCond',
    'PavedDrive'
]
ordinal_categories = [
      ['Reg', 'IR1', 'IR2', 'IR3'],
      ['Gtl', 'Mod', 'Sev'],
      ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['NA', 'No', 'Mn', 'Av', 'Gd'],
      ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
      ['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
      ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ'],
      ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['NA', 'Unf', 'RFn', 'Fin'],
      ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['NA', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
      ['N', 'P', 'Y']
]
nominal_features = [
      'MSZoning', 'Street', 'LandContour', 'LotConfig',
      'Neighborhood', 'Condition1', 'Condition2',
      'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
      'Exterior1st', 'Exterior2nd', 'MasVnrType',
      'Foundation', 'Heating', 'CentralAir',
      'Electrical', 'GarageType', 'SaleType', 'SaleCondition'
]

# numerical pipeline
numerical_imputer = SimpleImputer(strategy='mean')
categorical_imputer = SimpleImputer(strategy='constant',fill_value='NA')

numerical_pipeline = Pipeline([
    ('num',numerical_imputer),
    ('scaler',StandardScaler())
])

# categorical pipelines
ordinal_pipeline = Pipeline([
    ('ord',categorical_imputer),
    ('ordencode',OrdinalEncoder(categories=ordinal_categories,handle_unknown='use_encoded_value',unknown_value=-1))
])

nominal_pipeline = Pipeline([
    ('nom',categorical_imputer),
    ('nomencode',OneHotEncoder(sparse_output=False,handle_unknown='ignore'))
])

# preprocessing pipeline
preprocessor_pipeline = ColumnTransformer([
    ('numerical',numerical_pipeline,numerical_features),
    ('ordinal',ordinal_pipeline,ordinal_features),
    ('nominal',nominal_pipeline,nominal_features)
])

# model pipeline
model_pipeline = Pipeline([
    ('preprocess',preprocessor_pipeline),
    ('model',Ridge())
])

model_pipeline.fit(X_train,y_train)

params={'model__alpha':[0.01,0.05,0.1,0.5,1,10,100,200,300]}
grid = GridSearchCV(model_pipeline,param_grid=params,scoring='neg_root_mean_squared_error',cv=5)
grid.fit(X_train,y_train)
grid.best_params_

y_pred = grid.predict(X_test)
r2 = r2_score(y_test,y_pred)
r2

with open(r'D:\Projects\Prodigy-Projects\PRODIGY_ML_01\house_price_predictor_model.pkl','wb') as f:
  pickle.dump(grid,f)

